// Code generated by log-gen. DO NOT EDIT.
package models

import "time"

type ShopOrder struct {
	Id          int64     `json:"id"`//
	Uuid        string    `json:"uuid"`//'uuid，为兼容旧逻辑',
	UserId      int64     `json:"user_id"`//'购买用户id',
	Payment     int8      `json:"payment"`//'0-no,1-wepay,2-alipay',
	FeeAmount   int       `json:"fee_amount"`//'总共需要支付费用',
	PrepareTime int       `json:"prepare_time"`//'发起支付时间,10位时间戳',
	PaidTime    int       `json:"paid_time"`//'回调确认支付时间',
	GoodsDetail string    `json:"goods_detail"`//'订单商品详情，json数组',
	Status      int8      `json:"status"`//'1-待支付,3-待确认,4-已经支付成功,5-支付失败,6-物流中，7-关闭,8-完成',
	CreatedTs   time.Time `json:"created_ts"`//
	UpdatedTs   time.Time `json:"updated_ts"`//
	LogisticsId int64     `json:"logistics_id"`//'物流id',
	Flag        int       `json:"flag"`//'01-已计算sold_amount,10-已经评论',
}

func (s *ShopOrder) Pk() string {
	return "id"
}
func (s *ShopOrder) TableName() string {
	return "shop_order"
}
